# Generated by Django 6.0.6 on 2026-06-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('IMPORTED', 'Imported'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='groups.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('split_type', models.CharField(blank=True, max_length=50, null=True)),
                ('split_with', models.TextField(blank=True, null=True)),
                ('split_details', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('resolved_description', models.CharField(blank=True, max_length=255, null=True)),
                ('resolved_paid_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resolved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('resolved_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('resolved_split_type', models.CharField(blank=True, max_length=20, null=True)),
                ('resolved_split_with', models.TextField(blank=True, null=True)),
                ('resolved_split_details', models.TextField(blank=True, null=True)),
                ('resolved_notes', models.TextField(blank=True, null=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('original_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_imported', models.BooleanField(default=False)),
                ('is_settlement', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importsession')),
            ],
        ),
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], max_length=10)),
                ('raw_value', models.TextField()),
                ('suggested_fix', models.TextField()),
                ('decision', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited')], default='PENDING', max_length=20)),
                ('resolved_value', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importrow')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importsession')),
            ],
        ),
    ]
